name: ADHDTimerApp
options:
  bundleIdPrefix: com.adhd
  deploymentTarget:
    iOS: "16.0"
targets:
  ADHDTimerApp:
    type: application
    platform: iOS
    sources:
      - ADHDTimerApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.adhd.timer
      INFOPLIST_FILE: ADHDTimerApp/Info.plist
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      TARGETED_DEVICE_FAMILY: "1,2"
      SUPPORTS_MACCATALYST: false
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      GENERATE_INFOPLIST_FILE: true
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
      INFOPLIST_KEY_UILaunchScreen_Generation: true
      INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      SWIFT_VERSION: "5.0"
